$ANSIBLE_VAULT;1.1;AES256
66383935646238303936373561383037633663386263616433323338313962363335623165343337
6532373665363835613133376435663038663266343230330a393462313837663833393861313231
33333530613065386164326534393661663164393638383438303062626561393030396561643337
3030373165366265370a343962663563653834666536366162663936663739666134666337353134
65366430643131343861373862666264386663633532343230333066613561323738326430393739
38323166346137633066353962306233343031306237626662646438643634643661626438613138
37646362616235356662623664646531383533343066383235343630376164616664613235666261
62343863316364636261383936396666343565363531613330333439613631343664663235383561
64363561616664346237633032363663323132666638666634666665646362393962653762643764
35636434313161636231333337616465323834643933373934313032323934633961373366393039
33326464386539346631383633666430306565303864336366613533363932633964393766373332
34626537613431393765366230643137386338343237326230303535386264643762356665346533
64656365396664376566313836623232366464303835623031633765363135646135376432643563
34306636373264346331333764623437356132396163343562393333613238333234663661653632
38306666393536663732653865303932613631363737313237613132376430643439646630366232
62623665616238323731356530383233393136663264396662396464303136313230333965363837
61633139323236396430343963386333626230313538626261653931653035643364383936663338
33353963653365323533326664353963323332316361346234353132306562313738333637393539
323036616433633135323461643634633234
