$ANSIBLE_VAULT;1.1;AES256
64633063613837303866646561633432326531393635313963666563663631663261656234616366
3463376663373164663132333934333933313763393430660a613734326635396335323364663736
61346264663130343533346433623261316461613564646662613230353361386433346630383263
3330613334363936350a313539333763376531303230626438306432366638316532396637626133
66613638623233656231376531626661383166613633646465303361653165656265623961626564
66383065616461363337326432306631343935336431333666326331383064373537336565346137
63613536623265313066366261666630643265613631366461653835363339363765313835336135
63623364613031343036343566383535623130353430316437376165616461343964346432336135
65623235386436333361646239616365356536396332386663623965343463326334396131313961
63376161313733366635396462363833356434653965343866383339656533363238343736383461
65333861386261336331313364636535616261326534636135326264666462313136313938343837
61616665366638393431366636623039313765313731356432343366663331643334333232336436
62646236383334633733316234323166616565653937336466336530653162366163656666313832
36666665363362323231633539633534636437333236613032383832336434323965643135623230
34643631346633366237653132306635633162383735366366323462353335323533353434373937
34316536356166313664333034613566633836623863363763356431323839386363656330666438
35373364383330613664323662636237313531353663303865623931646165326461616134653030
31393038616661386636363033326534613638623837643666666537653661643035663333623831
34613131333662333637623038313236666464656335373236646161666539633235636535646134
32613732393431323136613232366333623739333865336633333031613537643762663338636533
33613066366232343939353665653134666335353562316634623966613462386539666665373135
64343564323464633262333362356631313330633430623734333439393230613435393262306539
34373532373763393730373837383665393038363831623964326430613266326435646338346530
30303336333966626462636462656261396336346437333339383532616335323562653337653231
33313363646463303237333064386439616561336230643132636339386166643730313266393730
3739366433333034316664623263663263333862616564366563
