$ANSIBLE_VAULT;1.1;AES256
63633336653534326138656465393865363861643066626663316463653762333831373639613837
6337366162656334633036353636343938356262626465650a623735353564653936636430396433
66363965363931653661633037376566356334396662343161626431336662383065393164306333
3531326439353062630a383861313639353062343034386366626265356536623935616161646466
65323536306239626632366331613938386131373432356135616266323766643839626464336638
31396231356666376134373635336537656432383364303430356236633632363932313366653539
33393566356232396330313731653934316435353733373338626564613139373365326261623536
66313538336162613464303665346563336336633036646135366561343263343565613632316531
37636234643930663334356361613338623332316337356261663238333632366265636437346230
3532613162386463643735626437646535646537346430646138
