$ANSIBLE_VAULT;1.1;AES256
38376432623831366232396236383063646538653939383036303763366363666637623462643466
6263646632386234383830646634363438636465633461330a643630303138646131303461636265
31386531616632616431643439363932336335633339376565636135646263393234323761653135
6364646461613733610a613664343031323532653531363766303136386536666164633865313438
64386639353939663165643463646636653864666636383639356137303931373839373433363039
39333232623930656566633265313566346263353863353431303533663734313637636536653661
39343933333734373361383362366237376435626563386164623630353031613930343138636162
32653434616130323563616536333537613962383330373835363162656331643738353964656466
62353136323835646631656561623163373765643432376239323130373161313439393232616234
3637666633636133306462643834326334333934636434306635
