---
# Connection defaults for monitoring targets (Splunk host(s))
ansible_user: sysadmin
ansible_python_interpreter: /usr/bin/python3

ansible_become: true
ansible_become_method: sudo

ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
ansible_timeout: 10
